config/routes.rb
Rails.application.routes.draw do
  root to: 'cheques#index'
  resources :cheques, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cheque.rb
class Cheque < ApplicationRecord
  validates :recipient_name, :payment_date, :amount, presence: true
  validates :amount, numericality: true, allow_blank: true

  scope :by_name, -> (recipient_name) { where(recipient_name: recipient_name ) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cheques_controller.rb
class ChequesController < ApplicationController
  before_action :set_cheque, only: :show

  # List of cheques
  # ====URL
  #    /cheques [GET]
  # ====Filter Parameters
  #   recipient_name
  def index
    if params.dig(:recipient_name)
      @cheques = Cheque.by_name(params[:recipient_name]).order(created_at: :desc)
    else
      @cheques = Cheque.order(created_at: :desc)
    end
  end

  # View cheque
  # ====URL
  #    /cheques/:ID [GET]
  def show
  end

  # GET /cheques/new
  def new
    @cheque = Cheque.new
  end


  # Create a cheque
  # ====URL
  #    /cheques [POST]
  # ====Parameters
  #   cheque[recipient_name]
  #   cheque[payment_date]
  #   cheque[amount]
  def create
    @cheque = Cheque.new(cheque_params)
    if @cheque.save
      redirect_to @cheque, notice: 'Cheque was successfully created.'
    else
      render :new
    end
  end

  private

    def set_cheque
      @cheque = Cheque.find(params[:id])
    end

    def cheque_params
      params.require(:cheque).permit(:recipient_name, :payment_date, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cheques/_form.html.erb
<%= form_for(@cheque, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @cheque.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@cheque.errors.count, "error") %> prohibited this cheque from being saved:</h4>

      <ul>
      <% @cheque.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :recipient_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :recipient_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :payment_date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :payment_date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :amount, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/cheques/index.html.erb
<div class="page-header">
  <%= link_to new_cheque_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Cheque
  <% end %>
  <h1>Listing cheques</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Recipient name</th>
        <th>Payment date</th>
        <th>Amount</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @cheques) do |cheque| %>
        <td>
          <%= link_to cheque.recipient_name, cheques_path(recipient_name: cheque.recipient_name) %>
        </td>

        <td><%= cheque.payment_date %></td>

        <td><%= number_with_delimiter(cheque.amount, delimiter: ',') %></td>

        <td><%= link_to 'View', cheque %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/cheques/new.html.erb
<div class="page-header">
  <%= link_to cheques_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New cheque</h1>
</div>

<%= render 'form' %>

app/views/cheques/show.html.erb
<div class="page-header">
  <%= link_to cheques_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Show cheque</h1>
</div>

<dl class="dl-horizontal">
  <dt>Recipient name:</dt>
  <dd><%= @cheque.recipient_name %></dd>

  <dt>Payment date:</dt>
  <dd><%= @cheque.payment_date %></dd>

  <dt>Amount:</dt>
  <dd><%= number_with_delimiter(@cheque.amount, delimiter: ',') %></dd>

  <dt>Amount in words:</dt>
  <dd><%= NumbersInWords.in_words(@cheque.amount).humanize %></dd>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Print Cheque App</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Print Cheque App", root_path, class: "navbar-brand" %>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>